{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "# module to create matrix \n",
    "import numpy as np\n",
    "\n",
    "#assigning sequences \n",
    "seq1= 'ATCGATCG'\n",
    "seq2= 'AGCTAG'\n",
    "\n",
    "#scoring scheme declared as global variables \n",
    "match = +1;\n",
    "mis_match = 0;\n",
    "gap_penalty = -1\n",
    "\n",
    "#matrix of length of both the sequences +1 (row and column each) to accomodate the gap penatly\n",
    "#as global variable so that can be used by all functions \n",
    "boxes= np.zeros((len(seq2) + 1, len(seq1) +1))\n",
    "         "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "seq1 bp 1 matches with seq2 bp  1\n",
      "seq1 bp 1 matches with seq2 bp  5\n",
      "seq1 bp 2 matches with seq2 bp  4\n",
      "seq1 bp 3 matches with seq2 bp  3\n",
      "seq1 bp 4 matches with seq2 bp  2\n",
      "seq1 bp 4 matches with seq2 bp  6\n",
      "seq1 bp 5 matches with seq2 bp  1\n",
      "seq1 bp 5 matches with seq2 bp  5\n",
      "seq1 bp 6 matches with seq2 bp  4\n",
      "seq1 bp 7 matches with seq2 bp  3\n",
      "seq1 bp 8 matches with seq2 bp  2\n",
      "seq1 bp 8 matches with seq2 bp  6\n",
      "total matches are = 12\n",
      "Optimal alignment with Needleman Wunsch Algorithm is shown below: \n",
      "ATCGATCG\n",
      "A--GCTAG\n"
     ]
    }
   ],
   "source": [
    "'''calculate the score for each base pair of the 2 sequences '''\n",
    "\n",
    "#dot plot incorporated from problem 3.2 \n",
    "def dotcounter(seq1,seq2):\n",
    "    count=0;\n",
    "    for i in range(len(seq1)):\n",
    "        for j in range(len(seq2)):\n",
    "            if seq1[i] == seq2[j]:\n",
    "                print('seq1 bp', i+1, 'matches with', 'seq2 bp ', j+1)\n",
    "                count += 1;\n",
    "    print(\"total matches are =\", count)\n",
    "\n",
    "\n",
    "# function created for calcualting the score by passing 2 argumments \n",
    "def score(bp1, bp2):\n",
    "    if bp1 == bp2:\n",
    "        return match;\n",
    "    elif bp1 == '-' or bp2 == '-':\n",
    "        return gap_penalty\n",
    "    else:\n",
    "        return mis_match\n",
    "\n",
    "\n",
    "'''actual Needleman Wunsch alginment goes here'''\n",
    "\n",
    "\n",
    "def global_alignment_matrix(seq1, seq2):\n",
    "    dotcounter(seq1, seq2)\n",
    "    \n",
    "    #these variables stores the len of sequences that will be used to execute the for loop \n",
    "    num_cols = len(seq1)\n",
    "    num_rows = len(seq2)\n",
    "     \n",
    "    # assiging values to the first row with -1, -2 etc.\n",
    "    for i in range(0, num_cols +1 ):\n",
    "        boxes[0][i] = gap_penalty * i;\n",
    "    \n",
    "    #assiging values to first column with -1, -2 etc\n",
    "    for j in range(0, num_rows + 1 ):\n",
    "        boxes[j][0] = gap_penalty * j;\n",
    "    \n",
    "    #nested for loop to access each element of the matrix \n",
    "    for row in range(1, num_rows + 1):\n",
    "        for col in range(1, num_cols + 1):\n",
    "            \n",
    "            #\n",
    "            diagonal= boxes [ row-1 ][ col-1 ] + score( seq1[ col-1 ], seq2 [ row-1 ])\n",
    "            delete = boxes[ row - 1][col] + gap_penalty\n",
    "            insert = boxes[row][col - 1] + gap_penalty\n",
    "            \n",
    "            # Record the maximum score from the three possible scores calculated above\n",
    "            boxes[row][col] = max(diagonal, delete, insert)\n",
    "    \n",
    "    \n",
    "    '''tracing back by checking the value of the current cell matches with the diagonal, up or left of the cell'''\n",
    "    # 2 empty strings \n",
    "    alignment_1 = ''\n",
    "    alignment_2 = ''\n",
    "    \n",
    "    #for the last cell of the matrix \n",
    "    back_i = len(seq2)\n",
    "    back_j = len(seq1)\n",
    "    \n",
    "    #loop till the pointer reaches the first row first column cell\n",
    "    while back_i > 0 and back_j > 0:\n",
    "        \n",
    "        #variblaes for position/coordinates of current, diagonla, up and left cells\n",
    "        current_box = boxes [back_i] [back_j];\n",
    "        diagonal_box = boxes [back_i -1] [back_j-1]\n",
    "        up_box = boxes[back_i] [ back_j -1]\n",
    "        left_box = boxes[back_i -1] [back_j]\n",
    "        \n",
    "        #check if current cell score matches the diagonal score. if yes, add the base pair to empty string \n",
    "        if current_box == diagonal_box + score( seq1[ back_j-1 ], seq2 [ back_i-1 ]):\n",
    "            alignment_1 += seq1[back_j-1]\n",
    "            alignment_2 += seq2[back_i-1]\n",
    "            \n",
    "            #one less of each column and row\n",
    "            back_i -= 1\n",
    "            back_j -= 1\n",
    "        \n",
    "        #check if current box score matches up cell + (-1) \n",
    "        elif current_box == up_box + gap_penalty:\n",
    "            alignment_1 += seq1[back_j-1]\n",
    "            alignment_2 += '-'\n",
    "            back_j -= 1 # move to one column left keeping row same \n",
    "            \n",
    "        #check if current box score matches left cell + (-1)\n",
    "        elif current_box == left_box + gap_penalty:\n",
    "            alignment_1 += '-'\n",
    "            alignment_2 += seq2[back_i -1]\n",
    "            back_i -=1; # moving one row above keeping column same \n",
    "            \n",
    "    \n",
    "    # as we had base pairs added back by tracing back, we got to print the reverse of the sequneces \n",
    "    alignment_1 = alignment_1[::-1]\n",
    "    alignment_2 = alignment_2[::-1]\n",
    "    \n",
    "    return(alignment_1, alignment_2)\n",
    "\n",
    "#creating objects by calling the function and passing the arguments \n",
    "align_sequence1, align_sequence2 = global_alignment_matrix(seq1, seq2)\n",
    "\n",
    "#print in different lines\n",
    "print(\"Optimal alignment with Needleman Wunsch Algorithm is shown below: \")\n",
    "print(align_sequence1 + \"\\n\" + align_sequence2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
